[workspace]
resolver = "2"

members = [
  "dxe_readiness_capture",
  "common",
  "dxe_readiness_validator",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "BSD-2-Clause-Patent"
description = "Dxe Readiness Capture/Validation Tool"

[workspace.dependencies]
cfg-if = "1.0.0"
section_extractor = { version = "9" }
stacktrace = { version = "9" }
uefi_sdk = { version = "3" }
log = { version = "^0.4", default-features = false, features = [
    "release_max_level_warn",
] }
spin = "^0.9"
mu_pi = { version = ">=5.2.1" }

[profile.dev]
opt-level = 3

[profile.test]
opt-level = 0
