[toolchain]
channel = "1.85.0"
targets = [
    "x86_64-unknown-uefi",
    "aarch64-unknown-uefi",
    "x86_64-pc-windows-msvc",
    "aarch64-pc-windows-msvc",
    "x86_64-unknown-linux-gnu",
    "aarch64-unknown-linux-gnu",
]
components = ["clippy", "rustfmt"]
