## @file
# Azure Pipeline build file for the repository
#
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: Apache-2.0
##

trigger: none
pr: none

resources:
  repositories:
    - repository: mu_devops
      type: github
      endpoint: microsoft
      name: microsoft/mu_devops
      ref: main

jobs:
- template: templates/Build.yml

